import {StyleSheet} from 'react-native';
import {colors, fontSize, sizes} from '../../services';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.bluishWhite,
    height: sizes.screenHeight,
  },
  backgroundColor: {
    backgroundColor: colors.pinkishwhite,
  },
  transparentBg: {
    paddingVertical: sizes.screenWidth * 0.06,
    // height: sizes.screenHeight * 0.1,
    width: sizes.screenWidth,
  },
  inputContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: sizes.screenWidth * 0.08,
    borderWidth: sizes.screenWidth * 0.003,
    borderColor: colors.emptyStar,
    marginHorizontal: sizes.screenWidth * 0.05,
    backgroundColor: colors.lightgray,
    height: sizes.screenHeight * 0.062,
    marginTop: sizes.screenHeight * 0.023,
    justifyContent: 'center',
  },
  search: {
    height: sizes.screenHeight * 0.024,
  },
  input: {
    color: colors.black,
    width: sizes.screenWidth * 0.78,
  },
  mapContainer: {
    marginTop: sizes.screenHeight * 0.07,
    height: sizes.screenHeight * 0.23,
    width: sizes.screenWidth * 0.9,
    borderRadius: sizes.screenWidth * 0.04,
    alignSelf: 'center',
    borderWidth: sizes.screenWidth * 0.002,
    borderColor: colors.darkerBordercolor,
    overflow: 'hidden',
  },
  topIconRow: {
    flexDirection: 'row',
    marginHorizontal: sizes.screenWidth * 0.05,
    // height: sizes.screenHeight * 0.064,
    // marginTop: sizes.screenHeight * 0.05,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locationRow: {
    flexDirection: 'row',
    height: sizes.screenHeight * 0.064,
    backgroundColor: colors.lightgray,
    borderRadius: sizes.screenWidth * 0.04,
    paddingHorizontal: sizes.screenWidth * 0.03,
    paddingVertical: sizes.screenHeight * 0.02,
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  locationDetailColumn: {
    marginStart: sizes.screenWidth * 0.02,
    marginEnd: sizes.screenWidth * 0.04,
  },
  nearbyTxt: {
    color: colors.gray,
    fontSize: fontSize.small,
    fontWeight: '400',
  },
  currentLocationTxt: {
    color: colors.black,
    fontSize: fontSize.small,
    fontWeight: 'bold',
  },
  locationContainertop: {
    backgroundColor: colors.pinkBtnbackground,
    height: sizes.screenHeight * 0.046,
    width: sizes.screenWidth * 0.09,
    borderRadius: sizes.screenWidth * 0.03,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationContainer: {
    backgroundColor: colors.lightgray,
    height: sizes.screenHeight * 0.064,
    width: sizes.screenWidth * 0.13,
    borderRadius: sizes.screenWidth * 0.03,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconImage: {
    height: sizes.screenHeight * 0.03,
    width: sizes.screenWidth * 0.042,
    resizeMode: 'contain',
  },
  otherIconRow: {
    flexDirection: 'row',
    height: sizes.screenHeight * 0.064,
    borderRadius: sizes.screenWidth * 0.04,
    alignItems: 'center',
    alignSelf: 'flex-end',
    justifyContent: 'space-between',
    width: sizes.screenWidth * 0.29,
  },
  containerBody: {
    marginTop: sizes.screenHeight * 0.01,
    paddingHorizontal: sizes.screenWidth * 0.06,
  },
  detailRow: {
    flexDirection: 'row',
    width: sizes.screenWidth * 0.88,
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  detailContainer: {
    backgroundColor: colors.grayBg,
    width: sizes.screenWidth * 0.43,
    borderRadius: sizes.screenWidth * 0.02,
    flexDirection: 'row',
    paddingHorizontal: sizes.screenWidth * 0.02,
    paddingBottom: sizes.screenHeight * 0.01,
    justifyContent: 'space-between',
  },
  boxImg: {
    height: sizes.screenHeight * 0.04,
    width: sizes.screenWidth * 0.05,
    resizeMode: 'contain',
  },
  detailTxt: {
    color: colors.blackishGray,
    fontWeight: '500',
    textAlign: 'right',
    fontSize: fontSize.small,
  },
  appoitmentNumberTxt: {
    color: colors.blackishGray,
    fontWeight: '500',
    fontSize: fontSize.h5,
    textAlign: 'right',
  },
  headingSummary: {
    // marginTop: sizes.screenHeight * 0.02,
    color: colors.black,
    fontSize: fontSize.medium,
    fontWeight: '500',
  },
  rowTwo: {
    marginTop: sizes.screenHeight * 0.03,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  lastServicesContainer: {
    marginTop: sizes.screenHeight * 0.01,
    // height: sizes.screenHeight * 0.35,
  },
  rowThree: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    width: sizes.screenWidth * 0.88,
    paddingHorizontal: sizes.screenWidth * 0.03,
    paddingVertical: sizes.screenWidth * 0.022,
    borderRadius: sizes.screenWidth * 0.02,
    borderColor: colors.emptyStar,
    borderWidth: sizes.screenWidth * 0.003,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  serviceHeading: {
    color: colors.black,
    fontSize: fontSize.smallM,
    width: sizes.screenWidth * 0.21,
  },
  priceHeading: {
    color: colors.black,
    fontSize: fontSize.smallM,
    marginStart: sizes.screenWidth * 0.06,
  },
  dateHeading: {
    color: colors.black,
    fontSize: fontSize.smallM,
    marginStart: sizes.screenWidth * 0.08,
  },
  statusHeading: {
    color: colors.black,
    fontSize: fontSize.smallM,
    marginStart: sizes.screenWidth * 0.06,
  },
  serviceDetailRow: {
    marginTop: sizes.screenHeight * 0.01,
    flexDirection: 'row',
    backgroundColor: colors.grayBg,
    width: sizes.screenWidth * 0.88,
    paddingHorizontal: sizes.screenWidth * 0.03,
    paddingVertical: sizes.screenWidth * 0.02,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: sizes.screenWidth * 0.03,
  },
  dateHeadingTwo: {
    color: colors.black,
    fontSize: fontSize.smallM,
    textAlign: 'center',
  },
  timeHeading: {
    color: colors.gray,
    fontSize: fontSize.smallM,
    textAlign: 'center',
  },
  statusHeadingTwo: {
    color: colors.red,
    fontSize: fontSize.smallM,
    width: sizes.screenWidth * 0.17,
    textAlign: 'right',
  },
  statusHeadingTwoIOS: {
    color: colors.red,
    fontSize: fontSize.smallM,
    width: sizes.screenWidth * 0.17,
    textAlign: 'right',
    // backgroundColor:'white'
  },
  priceHeadingTwo: {
    color: colors.black,
    fontSize: fontSize.smallM,
    width: sizes.screenWidth * 0.1,
    // textAlign:'left',
    fontWeight: '500',
    // backgroundColor:'red'
  },
  reviewHeading: {
    color: colors.black,
    fontSize: fontSize.large,
    fontWeight: '500',
  },
  rowFour: {
    marginTop: sizes.screenHeight * 0.02,
    // marginTop: sizes.screenHeight * 0.04,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  viewAllBtn: {
    borderColor: colors.red,
    alignItems: 'center',
    borderWidth: sizes.screenWidth * 0.003,
    width: sizes.screenWidth * 0.23,
    paddingVertical: sizes.screenHeight * 0.007,
    borderRadius: sizes.screenWidth * 0.05,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  viewAllText: {
    color: colors.red,
    fontSize: fontSize.smallM,
    fontWeight: '500',
  },
  arrowImage: {
    resizeMode: 'contain',
    width: sizes.screenWidth * 0.025,
    marginStart: sizes.screenWidth * 0.01,
  },
  reviewContainer: {
    marginTop: sizes.screenHeight * 0.01,
    paddingHorizontal: sizes.screenWidth * 0.03,
    paddingVertical: sizes.screenWidth * 0.022,
    borderRadius: sizes.screenWidth * 0.03,
    borderColor: colors.emptyStar,
    borderWidth: sizes.screenWidth * 0.003,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  reviewInsideContainer: {
    alignItems: 'center',
  },
  ratingNumber: {
    color: colors.black,
    fontSize: fontSize.h5,
    fontWeight: '900',
  },
  startContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: sizes.screenWidth * 0.0222,
    height: sizes.screenHeight * 0.022,
  },
  totalReview: {
    color: colors.grayText,
    marginTop: sizes.screenHeight * 0.013,
  },
  reviewBarContainer: {
    width: sizes.screenWidth * 0.45,
  },
  reviewBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingGoldenText: {
    color: colors.goldText,
    fontSize: fontSize.smallM,
    fontWeight: '500',
    marginEnd: sizes.screenWidth * 0.01,
  },
  percentGoldenText: {
    color: colors.goldText,
    fontSize: fontSize.smallM,
    fontWeight: '500',
    marginStart: sizes.screenWidth * 0.02,
  },
  starImage: {
    marginEnd: sizes.screenWidth * 0.02,
  },
  ratingContainer: {
    alignItems: 'center',
    borderRadius: sizes.screenWidth * 0.03,
    borderColor: colors.emptyStar,
    borderWidth: sizes.screenWidth * 0.003,
    marginTop: sizes.screenHeight * 0.012,
    // backgroundColor: colors.red,
  },
  ratingData: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: sizes.screenWidth * 0.81,
    alignItems: 'center',
    marginTop: sizes.screenHeight * 0.012,
  },
  profilePic: {
    borderRadius: 60,
    height: 50,
    width: 50,
    resizeMode: 'contain',
  },
  alignItems: {
    marginLeft: sizes.screenWidth * 0.05,
    marginTop: sizes.screenHeight * 0.0122,
  },
  usernameAllignment: {
    fontSize: fontSize.small,
    fontWeight: '700',
    color: colors.black,
  },
  time: {
    fontSize: fontSize.small,
    color: colors.grayText,
  },
  startContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: sizes.screenWidth * 0.0222,
    height: sizes.screenHeight * 0.022,
  },
  descriptionContainer: {
    color: colors.grayText,
    fontSize: fontSize.small,
    marginTop: sizes.screenHeight * 0.012,
    marginRight: sizes.screenWidth * 0.022,
    marginLeft: sizes.screenWidth * 0.03,
    marginBottom: sizes.screenHeight * 0.02,
    alignSelf: 'flex-start',
  },
  rowAndmargin: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ScrollViewContainer: {
    // marginTop: sizes.screenHeight * 0.01,
    marginBottom: sizes.screenHeight * 0.078,
  },

  paddingBtm: {
    paddingBottom: sizes.screenHeight * 0.1,
  },

  appointmentStyle: {
    resizeMode: 'contain',
    width: sizes.screenWidth * 0.1,
    height: sizes.screenWidth * 0.1,
  },

  noAppointmentMainView: {
    // flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: sizes.screenHeight * 0.025,
  },

  appointmentText: {
    color: colors.black,
    fontSize: fontSize.medium,
    marginLeft: 5,
    textAlign: 'center',
    width: sizes.screenWidth * 0.7,
  },

  appointmentBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: sizes.screenHeight * 0.01,
  },
});
