import { StyleSheet } from 'react-native';
import { colors, fontSize, sizes } from '../../services';
import Signup from '../Signup';
export const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.lightgray,
    height: sizes.screenHeight,
  },
  headerImage: {
    height: sizes.screenHeight * 0.32,
    width: sizes.screenWidth,
    borderBottomLeftRadius: sizes.screenWidth * 0.0562,
    borderBottomRightRadius: sizes.screenWidth * 0.0562,
  },
  headerContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: sizes.screenWidth * 0.05,
    marginTop: sizes.screenHeight * 0.05,
  },
  bookMarkedConatiner: {
    height: 44,
    width: 44,
    backgroundColor: '#00000099',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookMarkedConatiner2: {
    height: 44,
    width: 44,
    backgroundColor: '#ffffff99',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookMarkedFalse: {
    height: 24,
    resizeMode: 'contain',
  },
  openButtonborder: {
    borderStyle: 'solid',
    borderColor: colors.white,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00000044',
    paddingHorizontal: 20,
    paddingVertical: 2,
  },
  openButton: {
    fontSize: fontSize.smallM,
    color: colors.white,
    bottom: 1,
  },
  openBg: {
    alignItems: 'center',
    width: sizes.screenWidth * 0.148,
    height: sizes.screenHeight * 0.021,
    justifyContent: 'center',
  },
  barberDetailscontainer: {
    backgroundColor: colors.lightgray,
    borderStyle: 'solid',
    borderWidth: sizes.screenWidth * 0.002,
    borderColor: colors.lightGray2,
    borderRadius: sizes.screenWidth * 0.02,
    height: sizes.screenHeight * 0.08,
    width: sizes.screenWidth * 0.79,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  centerContent: {
    marginTop: sizes.screenHeight * 0.12,
    alignItems: 'center',
  },
  alignedDetails: {
    alignItems: 'center',
  },
  maleContainer: {
    height: sizes.screenWidth * 0.3,
    width: sizes.screenWidth * 0.3,
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: 'white',
    borderRadius: sizes.screenWidth * 0.3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    // Shadow properties for iOS
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    // Elevation for Android
    elevation: 5,
  },
  male: {
    height: sizes.screenWidth * 0.3,
    width: sizes.screenWidth * 0.3,
    borderRadius: sizes.screenWidth * 0.3,
  },
  barberNameContainer: {
    borderWidth: 1,
    borderRadius: 12,
    borderColor: colors.disabledBg,
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginVertical: 8,
  },
  barberName: {
    fontSize: fontSize.large,
    marginLeft: sizes.screenWidth * 0.012,
    color: colors.black,
    fontWeight: '800',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  row2: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  row3: {
    flexDirection: 'row',
    alignItems: 'center',
    width: sizes.screenWidth * 0.9,
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  disabledText: {
    color: colors.disabledBg2,
  },
  reviewBtn: {
    width: sizes.screenWidth * 0.34,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: colors.black,
  },
  pencil: {
    resizeMode: 'contain',
    height: 16,
    width: 16,
    marginRight: 8,
  },
  reviewBtnText: {
    color: colors.black,
    fontSize: fontSize.regular,
  },
  barberLocation: {
    fontSize: fontSize.small,
    color: colors.grayText,
    maxWidth: sizes.screenWidth * 0.7,
    textAlign: 'center'
  },
  redLocation: {
    justifyContent: 'flex-start',
    paddingRight: sizes.screenWidth * 0.021,
    height: sizes.screenHeight * 0.021,
    tintColor: colors.black
    // backgroundColor : 'red',
  },
  containBookmark: {
    marginTop: sizes.screenHeight * 0.022,
    marginRight: sizes.screenHeight * 0.022,
    // backgroundColor: 'red',
    height: sizes.screenHeight * 0.0322,
    justifyContent: 'center',
    width: sizes.screenWidth * 0.054,
    alignItems: 'center',
  },
  bookmark: {
    height: sizes.screenHeight * 0.0262,
  },
  todoButtonscontainer: {
    marginTop: sizes.screenHeight * 0.032,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignSelf: 'center',
    width: sizes.screenWidth * 0.7,
  },
  devider: {
    backgroundColor: colors.grayBorder,
    width: 1,
    height: sizes.screenHeight * 0.07,
  },
  btnColor: {
    backgroundColor: colors.grayBorder,
    alignItems: 'center',
    justifyContent: 'center',
    height: sizes.screenHeight * 0.058,
    width: sizes.screenWidth * 0.19,
    borderRadius: 16,
    // marginRight: sizes.screenWidth * 0.03,
    // marginLeft: sizes.screenWidth * 0.03,
    flexDirection: 'row',
  },
  direction: {
    height: 20,
    tintColor: colors.black
  },
  btnText: {
    color: colors.disabledBg2,
    fontSize: fontSize.smallM,
    marginTop: 8,
    alignSelf: 'center',
  },
  tabContainer: {
    marginTop: sizes.screenHeight * 0.032,
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    borderStyle: 'solid',
    borderBottomWidth: 1,
  },
  tabs: {
    color: colors.black,
    fontWeight: '500',
    marginBottom: sizes.screenHeight * 0.012,
    fontSize: fontSize.medium,
    width: sizes.screenWidth * 0.2,
    textAlign: 'center',
  },
  borderBottom: {
    borderBottomWidth: sizes.screenWidth * 0.013,
    borderStyle: 'solid',
  },
  aboutContent: {
    color: colors.grayText,
    marginTop: sizes.screenHeight * 0.004,
    marginLeft: sizes.screenWidth * 0.092,
    marginRight: sizes.screenWidth * 0.092,
    // height:sizes.screenHeight * 0.25
  },
  btn: {
    position: 'absolute',
    top: sizes.screenHeight * 0.25,
    left: sizes.screenWidth * 0.08,
  },
  btnIOS: {
    position: 'absolute',
    bottom: 0,
    alignSelf: 'center',
    // top: sizes.screenHeight * 0.3,
    // left: sizes.screenWidth * 0.08,
  },
  servicesContainer: {
    flexDirection: 'row',
    marginTop: sizes.screenHeight * 0.02,
    marginLeft: sizes.screenWidth * 0.0522,
    marginRight: sizes.screenWidth * 0.082,
    // paddingBottom : sizes.screenHeight * 0.030,
    // backgroundColor : 'red',
    width: sizes.screenWidth * 0.89,
    justifyContent: 'space-between',
  },
  serviceImagecontainer: {
    backgroundColor: colors.selectorcolor,
    width: sizes.screenWidth * 0.17,
    height: sizes.screenHeight * 0.082,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: sizes.screenWidth * 0.04,
  },
  serviceImageresize: {
    height: sizes.screenWidth * 0.1,
    width: sizes.screenWidth * 0.1,
  },
  flexCol: {
    marginTop: sizes.screenHeight * 0.012,
    marginLeft: sizes.screenWidth * 0.022,
    flexDirection: 'column',
    // backgroundColor: 'red',
    width: sizes.screenWidth * 0.472,
  },
  title: {
    color: colors.black,
    fontWeight: '800',
  },
  description: {
    color: colors.grayText,
    fontSize: fontSize.small,
  },
  serviceTime: {
    color: colors.grayText,
    fontSize: fontSize.small,
    marginTop: sizes.screenHeight * 0.012,
    marginLeft: sizes.screenWidth * 0.042,
  },
  descriptionExtended: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  bookButton: {
    backgroundColor: colors.black,
    marginLeft: sizes.screenWidth * 0.022,
    marginBottom: sizes.screenHeight * 0.005,
    height: sizes.screenHeight * 0.027,
    width: sizes.screenWidth * 0.16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: sizes.screenWidth * 0.02,
  },
  bookWhite: {
    color: colors.white,
    fontSize: fontSize.small,
  },
  endContainer: {
    // backgroundColor: 'orange',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  serviceSpacebottom: {
    marginBottom: sizes.screenHeight * 0.03,
  },
  reviewsCenter: {
    alignItems: 'center',
    marginTop: sizes.screenHeight * 0.028,
    borderStyle: 'solid',
    borderBottomWidth: 0.4,
  },
  starNumber: {
    color: colors.black,
    fontSize: fontSize.h5,
    fontWeight: '900',
  },
  ratingContainer: {
    alignItems: 'center',
    borderStyle: 'solid',
    marginLeft: sizes.screenWidth * 0.0312,
    marginRight: sizes.screenWidth * 0.0312,
    borderWidth: sizes.screenWidth * 0.005,
    borderColor: colors.bordercolorgray,
    borderRadius: sizes.screenWidth * 0.02,
    marginTop: sizes.screenHeight * 0.012,
  },
  ratingData: {
    marginRight: sizes.screenWidth * 0.122,
    marginLeft: sizes.screenWidth * 0.122,
    justifyContent: 'space-between',
    flexDirection: 'row',
    // backgroundColor: 'orange',
    width: sizes.screenWidth * 0.812,
    alignItems: 'center',
    marginTop: sizes.screenHeight * 0.012,
  },
  profilePic: {
    borderRadius: sizes.screenWidth * 0.3,
    height: sizes.screenHeight * 0.052,
    width: sizes.screenWidth * 0.11,
  },
  rowAndmargin: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  alignItems: {
    marginLeft: sizes.screenWidth * 0.072,
    marginTop: sizes.screenHeight * 0.0122,
  },
  usernameAllignment: {
    fontSize: fontSize.small,
    fontWeight: '700',
    color: colors.black,
  },
  time: {
    fontSize: fontSize.small,
    color: colors.grayText,
  },
  startContainer: {
    // backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    width: sizes.screenWidth * 0.0222,
    height: sizes.screenHeight * 0.022,
  },
  descriptionContainer: {
    color: colors.grayText,
    fontSize: fontSize.small,
    marginTop: sizes.screenHeight * 0.012,
    marginRight: sizes.screenWidth * 0.022,
    marginLeft: sizes.screenWidth * 0.03,
    marginBottom: sizes.screenHeight * 0.02,
    alignSelf: 'flex-start',
  },
  scrollView: {
    height: sizes.screenHeight * 0.28,
    marginTop: 10,
    // flex: 1,
  },
  // reviewContainer: {
  //   height : sizes.screenHeight
  // },
});